My First R Program

  1. Print

In [ ]:
print("I Love R Programming")

cat ("R"," Program")

[1] "I Love R Programming"
R  Program

2. variables and data types

In [ ]:
myString <- "I love R Programming"
print (myString)

wholeNum <- 10
floatingNum <- 9.9
isBool <- TRUE

class(wholeNum)
class(floatingNum)
class(isBool)

[1] "I love R Programming"

[1] "numeric"

[1] "numeric"

[1] "logical"

3. Numerical Operators

In [ ]:
x <- 10
y <- 3

add <- x + y
sub <- x - y
mult <- x * y
div <- x / y
mod <- x %% y
exp <- x ^ y

print(add)
print(sub)
print(mult)
print(div)
print(mod)
print(exp)

[1] 13
[1] 7
[1] 30
[1] 3.333333
[1] 1
[1] 1000

4. User Input

In [ ]:
name <- readline("Enter name: ")

cat("Welcome to R Programming: ", name)

Enter name: abi
Welcome to R Programming:  abi

5. Decision Making

In [ ]:
grade <- 80

if (grade < 75 ){
  print ("Failed")
}else{
  print ("Passed")
}

[1] "Passed"

6. Loop

In [ ]:
  for(i in 1:5){
    print(i)
  }

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5

7. Functions

In [ ]:
  addNumber <- function(a,b){
    return (a+b)
  }

  addNumber(3,7)

[1] 10

8. Vectors

In [ ]:
grades <- c(98,80,91,88,96)

grades

mean(grades)
max(grades)
min(grades)
length(grades)
median(grades)
summary(grades)

[1] 98 80 91 88 96

[1] 90.6

[1] 98

[1] 80

[1] 5

[1] 91

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
   80.0    88.0    91.0    90.6    96.0    98.0

9. Matrices

In [ ]:
A <- matrix(c(1,2,3,4,5,6),nrow=3)
A

     [,1] [,2]
[1,] 1    4
[2,] 2    5
[3,] 3    6

10. Lists

In [ ]:
students <- list(
name = "Ave",
course = "BSCS",
grade = 75
)

students

$name
[1] "Ave"

$course
[1] "BSCS"

$grade
[1] 75

11. Dataframe

In [ ]:
students <- data.frame(
  name = c("Pepito","Elsa","Anna"),
  course = c("BSCS","BSIT","BSA"),
  grade = c(75,80,79)
)

students

  name   course grade
1 Pepito BSCS   75
2 Elsa   BSIT   80
3 Anna   BSA    79

12. Write to CSV

In [ ]:
write.csv(students,"students.csv")

13. Read CSV File

In [ ]:
data <- read.csv("students.csv")